name: Neard binary and Docker image release

on:
  # Run when a new release or rc is created
  release:
    types: [published]
  push:
    branches: master

  workflow_dispatch:
    inputs:
      branch:
        default: 'master'
        description: "Nearcore branch to build and publish"
        type: string
        required: true

jobs:
  binary-release:
    name: "Build and publish neard binary"
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      id-token: write # required to use OIDC authentication

    steps:
      - name: Print git sha
        run: |
          echo $(git rev-parse HEAD)
    
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAGODAPLATFORM_GITHUB_TOKEN }}
          repository: PagodaPlatform/anshal-test-pagoda
          event-type: packer-build 
          client-payload: '{"source-image-family":"anshal-test"}'