name: Neard binary and Docker image release

on:
  # Run when a new release or rc is created
  release:
    types: [published]
  push:
    branches: master

  workflow_dispatch:
    inputs:
      branch:
        default: 'master'
        description: "Nearcore branch to build and publish"
        type: string
        required: true

jobs:
  binary-release:
    name: "Build and publish neard binary"
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      id-token: write # required to use OIDC authentication

    steps:
      - name: Print git sha
        run: |
          echo $(git rev-parse HEAD)
    
      - name: Repository Dispatch
        uses: actions/github-script@v5
        with:
          script: |
            const repo = 'PagodaPlatform/anshal-test-pagoda';  // Replace with the org/repo of the Build NEAR node image CI workflow
            const token = process.env.PAGODAPLATFORM_GITHUB_TOKEN;
            const payload = {
              event_type: 'packer-build',
              client_payload: {
                source_image_family: 'near-node-base',
                image_family: 'near-node',
                image_name: `near-node-${{ github.ref }}`  // Replace release-tag with the actual value
              }
            };
            const result = await github.repos.createDispatchEvent({
              owner: repo.split('/')[0],
              repo: repo.split('/')[1],
              event_type: payload.event_type,
              client_payload: payload.client_payload
            });
            return result;
          